// AUTO-GENERADO por migration (reemplaza el modulo virtual @/entities/all de Base44)
import { makeEntity, User } from '@/api/entityFactory';

export const Actividad = makeEntity('Actividad');
export const AjusteInicialInventario = makeEntity('AjusteInicialInventario');
export const AjusteInventario = makeEntity('AjusteInventario');
export const ArqueoCaja = makeEntity('ArqueoCaja');
export const AsientoContable = makeEntity('AsientoContable');
export const AvanceProduccionPCP = makeEntity('AvanceProduccionPCP');
export const Caja = makeEntity('Caja');
export const Cliente = makeEntity('Cliente');
export const ColorPintura = makeEntity('ColorPintura');
export const ComprobanteEgreso = makeEntity('ComprobanteEgreso');
export const ConciliacionBancaria = makeEntity('ConciliacionBancaria');
export const ConciliacionDetalle = makeEntity('ConciliacionDetalle');
export const CostoIndirecto = makeEntity('CostoIndirecto');
export const CuentaBancaria = makeEntity('CuentaBancaria');
export const CuentaContable = makeEntity('CuentaContable');
export const CuentaPorCobrar = makeEntity('CuentaPorCobrar');
export const CuentaPorPagar = makeEntity('CuentaPorPagar');
export const DocumentoInventario = makeEntity('DocumentoInventario');
export const Empleado = makeEntity('Empleado');
export const EntregaParcialPCP = makeEntity('EntregaParcialPCP');
export const Insumo = makeEntity('Insumo');
export const InventarioEnProceso = makeEntity('InventarioEnProceso');
export const MovimientoBancario = makeEntity('MovimientoBancario');
export const MovimientoCaja = makeEntity('MovimientoCaja');
export const MovimientoInventario = makeEntity('MovimientoInventario');
export const MovimientoLibroDiario = makeEntity('MovimientoLibroDiario');
export const OrdenCompra = makeEntity('OrdenCompra');
export const OrdenProduccionPCP = makeEntity('OrdenProduccionPCP');
export const OrdenVenta = makeEntity('OrdenVenta');
export const PedidoMarroquinero = makeEntity('PedidoMarroquinero');
export const PlacaPCP = makeEntity('PlacaPCP');
export const PlanCuentas = makeEntity('PlanCuentas');
export const ProcesoProduccion = makeEntity('ProcesoProduccion');
export const ProductoCatalogo = makeEntity('ProductoCatalogo');
export const ProductoTerminado = makeEntity('ProductoTerminado');
export const Proveedor = makeEntity('Proveedor');
export const RecetaPintura = makeEntity('RecetaPintura');
export const ReciboCaja = makeEntity('ReciboCaja');
export const Servicio = makeEntity('Servicio');
export const ServicioProduccion = makeEntity('ServicioProduccion');
export const SolicitudProduccion = makeEntity('SolicitudProduccion');
export const Tercero = makeEntity('Tercero');
export const TipoCueroPCP = makeEntity('TipoCueroPCP');
export const TipoGasto = makeEntity('TipoGasto');
export const TransferenciaCaja = makeEntity('TransferenciaCaja');
export const TransferenciaInterna = makeEntity('TransferenciaInterna');
export const TrasladoInventario = makeEntity('TrasladoInventario');
export const UnidadMedida = makeEntity('UnidadMedida');

export { User };
